version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "twitter-webhook-april-2022"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-47s1wlqhi2xv"
s3_prefix = "twitter-webhook-april-2022"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
profile = "samcli"
