AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Template for Webhooks API

Globals:
  Function:
    Timeout: 3

Parameters:
  TwitterApiSecret:
    Type: String
    Default: twitter.api.secret
    Description: Name of the parameter that will store Twitter API Key Secret, this is used by the CRC Lambda function. Manually create it in your account.

Resources:
  SAMTwitterWebhookActivity:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: twitter-webhook-activity/
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Environment:
        Variables:
          BUCKETNAME: !Ref BucketForOutputFile
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - s3:PutObject
              Resource: !Sub "arn:aws:s3:::${BucketForOutputFile}/*"
      Events:
        APIGateway:
          Type: Api
          Properties:
            Path: /webhook/twitter/cloudlopes
            Method: post
            
  SAMTwitterCRCResponse:
    DependsOn: BucketForOutputFile
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: twitter-crc-response/
      Handler: lambda_function.crc
      Runtime: python3.9
      Policies:
        - SSMParameterReadPolicy:
            ParameterName: !Ref TwitterApiSecret
      Environment:
        Variables:
          TWITTERAPISECRET: !Ref TwitterApiSecret
      Events:
        APIGateway:
          Type: Api
          Properties:
            Path: /webhook/twitter/cloudlopes
            Method: get

  BucketForOutputFile:
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: PublicRead
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - HEAD
            AllowedOrigins:
              - '*'

  SampleBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref BucketForOutputFile
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 's3:GetObject'
            Effect: Allow
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref BucketForOutputFile
                - /*
            Principal: '*'